apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
        name: helloworld
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: ${DOCKER_ADDRESS}/${IMAGE_NAME}:${VERSION}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "800m"
          limits:
            memory: "512Mi"
            cpu: "800m"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    name: helloworld
  ports:
  - port: 8080
    targetPort: 8080
    name: http
