version: 2.1 # use CircleCI 2.0
orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecr: circleci/aws-ecr@0.0.4
  kube-orb: circleci/kubernetes@0.11.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/circleci-demo-java-spring # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline # gets the project dependencies
      
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package # run the actual testsi
  deploy:  
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
      KOPS_STATE_STORE: s3://kopspoc.tk-state
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: "$AWS_ACCESS_KEY_ID"
          aws-secret-access-key: "$AWS_SECRET_ACCESS_KEY"
          aws-region: "$AWS_REGION"
      - kube-orb/install-kubectl     
      - kube-orb/install-kops
      - run:
          name: build and push image
          command: |
             docker --version
             eval $(aws ecr get-login --region us-east-1 --no-include-email)
             docker build -t terraform .
             docker tag terraform:latest 202771655335.dkr.ecr.us-east-1.amazonaws.com/terraform:latest
             docker push 202771655335.dkr.ecr.$AWS_REGION.amazonaws.com/terraform:latest
             kops export kubecfg kopspoc.tk
             HTTP_HOST=kopspoc.tk VERSION=$CIRCLE_SHA1 NAMESPACE=default < /home/ubuntu/kubernetes-aws-vpc-kops-terraform/gamutkart2/webapp/deployment.yml > /home/ubuntu/kubernetes-aws-vpc-kops-terraform/gamutkart2/webapp/deployment.yml
             kubectl -n default apply -f /home/ubuntu/kubernetes-aws-vpc-kops-terraform/gamutkart2/webapp/deployment.yml
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy
