apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
        name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: myapp
        image: 202771655335.dkr.ecr.us-east-1.amazonaws.com/terraform:latest
        ports:
        - name: html-port
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    name: webapp
  ports:
  - port: 80
    targetPort: 80
