apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
        name: helloworld
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: 202771655335.dkr.ecr.us-east-1.amazonaws.com/terraform:latest
        ports:
        - name: helloworld-port
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  type: LoadBalancer
  selector:
    name: helloworld
  ports:
  - port: 80
    targetPort: 8080

